# User config
author: "KO-YANG (Tyler), Chao"
tagline: "KO-YANG's Portfolio"
description: "Hi, I'm Tyler Chao — a robotics and technology enthusiast with a Master's in IT Engineering from Fachhochschule Wedel, Germany, 
              and a Bachelor's in Automatic Control Engineering from Feng Chia University, Taiwan.
              I've worked across embedded systems, IoT, and industrial robotics, 
              with hands-on experience in Python, Java, Embedded C, MQTT, RoboDK, and KUKA robots — always driven by a passion for building technology that makes a real impact."
email: "tylerchao2005@gmail.com"
resume: "https://drive.google.com/file/d/1d5dZAET6dd1LrJdmsG8yxI6ijcyw-9fw/view?usp=drive_link"
linkedin: "https://www.linkedin.com/in/ko-yang-chao-49b574216/"
github: "https://github.com/tylerchao"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed